### ISSUE TITLE
Reasoning behind parameter initialization?

### ISSUE THREAD

**Issue by adam-katona** [g1910/HyperNetworks#1]
Hi,

I was wondering what is the reason the hypernetwork parameters are initialized like this:
torch.fmod(torch.randn(dim),2)

By the way, thanks for the repo, it is awesome.

**Comment by g1910** [comment]
There is no specific reasoning behind doing this parameter initialization. You can do it any way you like (for example, using xavier initialization). Hope this helps! :)
