### ISSUE TITLE
I wonder if there are any experimental results for this implementation.

### ISSUE THREAD

**Issue by lynlynlyn** [g1910/HyperNetworks#2]
Thank you very much for the released code.
I wonder if there are any experimental results for this implementation.

**Comment by wangxu-scu** [comment]
Hi, I have run this code, but the final acc is about 84%, which is lower than the result 93.27% reported in the paper. What do you think about this result?

**Comment by g1910** [comment]
I could achieve an accuracy close to 91% with this implementation. I didn't spend a lot of time to optimize the training. If I remember correctly, the paper did not provide all the fine details to implement it identically. Please feel free to fork this and modify it to see if you can achieve better results.
