### ISSUE TITLE
Final Accuracy for CIFAR-10

### ISSUE THREAD

**Issue by jehoon1ee** [g1910/HyperNetworks#3]
Hi, Thank you for sharing your code.
Could I ask your final result of training this HyperNetwork code for CIFAR-10?

**Comment by g1910** [comment]
Hi, I could achieve an accuracy close to 91% with this implementation. I didn't spend a lot of time to optimize the training. If I remember correctly, the paper did not provide all the fine details to implement it identically. Please feel free to fork this and modify it to see if you can achieve better results. :)
